apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app
  labels:
    app.kubernetes.io/name: demo-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      relabelings:
        - targetLabel: application
          replacement: demo-app
