apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-dev
resources:
  - namespace.yaml
  - ../../base
images:
  - name: kalyanisai182/demo-app
    newTag: "cf07d5a"
patches:
  - path: deployment-patch.yaml
components:
  - ../../components/monitoring
